### PR TITLE
fix no_std

### LINKED ISSUE #125: no_std support is broken
I tried using this crate in a no_std context and it doesn't work because the inclusion of `num_traits::Float` isn't behind a feature flag, and evidently, the stuff behind the `libm_works` feature flag doesn't "work".

### PR DESCRIPTION
**Pull request by evq**
fixes #125

### CODE REVIEW

**Comment by Ogeon** [comment]
Cool, thank you for this! Is libm in a state where it can be used for the things we need now? That would be excellent! If this is all that's needed, it's definitely approved once the tests pass.

As for the test results, that overflow seems strange. I hope it's not something too nasty... Otherwise, I guess they had to tweak some inference rules since last time it ran.

**Comment by evq** [comment]
hey @Ogeon - looks like the overflow is due to the longstanding issue https://github.com/rust-lang-nursery/libm/issues/4 which was previously discussed in https://github.com/Ogeon/palette/pull/110. so to your question - I suppose libm is not yet fixed.

that libm issue is very interesting - it appears the overflow is intentional however it does not use `Wrapping` or `wrapped_add` and as such panics only in debug mode. meaning release mode is perfectly functional.

IMO having working `no_std` support with the caveat that there may be occasional spurious failures in debug mode far outweighs not having `no_std` support at all (current state). What are your thoughts on updating the documentation to highlight this caveat and move forward without waiting on libm?

**Comment by Ogeon** [comment]
Ah, that one. I more or less agree with you, but it requires a workaround that will also work for the tests. I'm not a fan of the thought of disabling overflow checks for the whole library, for example, but maybe that's what we have to do... We can't wait for libm to move if we want this within a foreseeable future, so unless a better alternative has appeared since last time i checked, we have to do what we can with what we have.

File: palette/src/convert.rs [hunk 1]
```diff
@@ -391,7 +391,7 @@ where
 ///         0.7353569830524495,
 ///         0.5370987304831942,
 ///     ];
-///     let hsv = Bgr::from_raw_slice(&buffer)[1].into();
+///     let hsv: Hsv<palette::encoding::Srgb, _> = Bgr::from_raw_slice(&buffer)[1].into();
```
Comment (Ogeon) [inline palette/src/convert.rs]: Wasn't just `Hsv` enough? `Srgb` should be the default.

Comment (evq) [reply palette/src/convert.rs]: yeah strangely enough, just `Hsv` didn't seem to be enough :(

Comment (Ogeon) [reply palette/src/convert.rs]: That's odd. Oh well. In that case can you add `Srgb` to the import at the top of the example? That would make this part a bit less noisy... I don't know if you tried it, but you may be able to skip the `_` at least, unless I'm forgetting something.

Comment (evq) [reply palette/src/convert.rs]: That would conflict with `palette::Srgb` imported above - do you have a preferred alias for the `Srgb` encoding? (e.g. `eSrgb` or similar?)

I have tried without the `_` and that doesn't seem to be enough.

**Comment by evq** [comment]
What do you think about creating multiple travis jobs? One runs tests with `std` as a required feature and the other runs tests with `--release` and would not have `std` as a required feature.

File: palette/src/convert.rs (hunk 1 above)
Comment (Ogeon) [reply palette/src/convert.rs]: Ugh, good job on me for not reading it all. It's also `f64`, not the default `f32`, so that's probably why `_` has to be there.

Uhm... I usually prefer to spell it out if I can... You could put a `self` in the encoding import and at least shorten it down to `encoding::Srgb`, I guess. :) If that makes a difference. I'm just trying to put the focus on the right hand expression, but it's not that important.

**Comment by Ogeon** [comment]
There's one script (test_features.sh) that runs all the features one by one. I suppose that one can run with `--release` instead. Then it will test with both in the same job. It's just too bad it's going to increase the build time, but let's try and see how big the impact is.

File: palette/src/convert.rs (hunk 1 above)
Comment (Ogeon) [reply palette/src/convert.rs]: Oh, you can create an alias like `type Hsv64 = Hsv<encoding::Srgb, f64>;`!

**Comment by evq** [comment]
If we only run with `--release` we might miss other overflow checks though. If we create two travis jobs  they can run in parallel so we can both get overflow checks except for `no_std` and test `no_std`.

**Comment by Ogeon** [comment]
I don't think it's going to be a problem, really. If you look at https://github.com/Ogeon/palette/blob/master/.travis.yml, it starts out by compiling and running with the default features. Then it runs the script and most of that script runs with `std` disabled. That's why we would not lose much on changing the script to run with `--release`. The alternative could be to change the script to run everything with `std` enabled, and then run a final test pass with everything disabled and `--release` enabled.

**Comment by Ogeon** [comment]
Also, I'm afraid we may be maxing out on parallel runners already, so I don't think we will save any time on that unless they increased the limit.

**Comment by Ogeon** [comment]
Sorry, I accidentally clicked the close and comment button.

**Comment by evq** [comment]
Ah gotcha! So we'd hit the default features in debug mode and individual features in release mode. That sounds good to me - will adjust

**Comment by Ogeon** [comment]
I think that will cover enough of the cases to give a good enough result. The optional features are mostly just utilities.

**Comment by evq** [comment]
@Ogeon I think this should be good to go now

**Comment by Ogeon** [comment]
Nice! I didn't have the time to check it until now, but it looks good! I'll try to get a release out this weekend. I would just like to check if the rest of the code is in a good state first.

**Comment by Ogeon** [comment]
bors: r+

**Comment by Ogeon** [comment]
Oh, and once again, thanks for the help!
